// ============================================================================
// JUDGE DASHBOARD TYPES & INTERFACES
// ============================================================================

export interface TimelineDataPoint {
  time: string;
  commits: number;
  phase: "setup" | "feature" | "fix";
}

export interface Milestone {
  name: string;
  timestamp: string;
}

export interface CodeEvolutionTimeline {
  timelineData: TimelineDataPoint[];
  phases: ("setup" | "feature" | "fix")[];
  milestones: Milestone[];
}

export interface Compliance {
  workDuringHackathonPct: number;
  commitTimingStatus: "Early" | "Late" | "Normal";
  locationStatusBadge: string;
  geoFenceWarnings: string[];
}

export interface MemberContribution {
  name: string;
  commits: number;
  linesAdded: number;
  percentage: number;
}

export interface ContributionFairness {
  memberContributions: MemberContribution[];
  fairnessScore: number;
  dominanceIndicator: string | null;
}

export interface IntegrityCodeQuality {
  preBuiltLikelihoodScore: number;
  externalHelpProbability: number;
  indicatorExplanations: string[];
  commitQualityScore: number;
  behavior: "Refactoring" | "Dumping";
  testCasesAdded: boolean;
}

export interface AutoGeneratedSummary {
  keyStrengths: string[];
  keyConcerns: string[];
  judgeNotes: string;
}

// ============================================================================
// Mentor & Judge Scoring
// ============================================================================
export interface JudgeMentorScore {
  id: string;
  name: string;
  role: "judge" | "mentor";
  score: number;
  maxScore: number;
  criteria?: string;
  timestamp?: string;
}

export interface TeamScores {
  scores: JudgeMentorScore[];
  totalScore: number;
  maxPossibleScore: number;
  averageScore: number;
}

// ============================================================================
// Remarks & Feedback System
// ============================================================================
export interface Remark {
  id: string;
  authorId: string;
  authorName: string;
  authorRole: "judge" | "mentor";
  content: string;
  category: "improvement" | "praise" | "concern" | "suggestion";
  timestamp: string;
  isAddressed: boolean;
  pointsAwarded?: number;
  addressedTimestamp?: string;
}

export interface TeamRemarks {
  remarks: Remark[];
  totalPointsAwarded: number;
  pendingImprovements: number;
  addressedImprovements: number;
}

export interface TeamSummary {
  id: string;
  teamName: string;
  repoLink: string;
  techStack: string[];
  finalScore: number;
}

export interface Team {
  summary: TeamSummary;
  codeEvolution: CodeEvolutionTimeline;
  compliance: Compliance;
  contributionFairness: ContributionFairness;
  integrityCodeQuality: IntegrityCodeQuality;
  autoGeneratedSummary: AutoGeneratedSummary;
  shortlisted: boolean;
  teamScores?: TeamScores;
  teamRemarks?: TeamRemarks;
}

export type SortOption = "fairness" | "innovation" | "violations";

export interface Toast {
  id: number;
  type: "success" | "warning" | "info" | "error";
  title: string;
  message: string;
}

export interface JudgeState {
  teams: Team[];
  selectedTeamId: string | null;
  sortBy: SortOption;
  filterShortlisted: boolean;
}

// ============================================================================
// Guidance Request Queue System
// ============================================================================
export interface TeamLocation {
  x: number; // Grid position X (0-100)
  y: number; // Grid position Y (0-100)
  zone: string; // e.g., "Zone A", "Zone B"
  tableNumber: string; // e.g., "A-12"
}

export interface MentorInfo {
  id: string;
  name: string;
  expertise: string[];
  currentLocation: TeamLocation;
  isAvailable: boolean;
  avatarUrl?: string;
}

export interface GuidanceRequest {
  id: string;
  teamId: string;
  teamName: string;
  teamLocation: TeamLocation;
  mentorId: string;
  mentorName: string;
  requestType: "technical" | "design" | "strategy" | "debugging" | "general";
  description: string;
  techStack: string[];
  priority: "low" | "medium" | "high" | "urgent";
  status: "pending" | "in-progress" | "resolved" | "cancelled";
  requestedAt: string;
  estimatedWaitTime?: number; // in minutes
  distanceFromMentor?: number; // calculated distance
  queuePosition?: number;
  // AI-suggested match scoring
  aiMatchScore?: number; // 0-100 score for best mentor/judge match
  aiMatchReasons?: string[]; // Reasons for the AI recommendation
  expertiseMatchPct?: number; // How well mentor expertise matches team tech stack
  suggestedMentorId?: string; // AI-suggested best mentor for this request
  suggestedMentorName?: string; // Name of suggested mentor
}

export interface GuidanceQueueState {
  requests: GuidanceRequest[];
  sortBy: "queue" | "distance" | "priority";
  filterStatus: "all" | "pending" | "in-progress";
  selectedMentorId: string | "all";
}

