import { useState, useEffect, useCallback } from "react";
import type { Team, Toast, JudgeState, SortOption } from "../types";
import { judgeService } from "../services";

// ============================================================================
// useJudge - Main hook for Judge Dashboard state
// ============================================================================
export function useJudge() {
  const [state, setState] = useState<JudgeState>({
    teams: [],
    selectedTeamId: null,
    sortBy: "fairness",
    filterShortlisted: false,
    isLoading: true,
    error: null,
  });

  // Fetch teams on mount
  useEffect(() => {
    const fetchTeams = async () => {
      try {
        const teams = await judgeService.getTeams();
        setState((prev) => ({
          ...prev,
          teams: judgeService.sortTeams(teams, prev.sortBy),
          selectedTeamId: teams[0]?.summary.id || null,
          isLoading: false,
        }));
      } catch (error) {
        setState((prev) => ({
          ...prev,
          isLoading: false,
          error: "Failed to load teams",
        }));
      }
    };
    fetchTeams();
  }, []);

  const selectTeam = useCallback((teamId: string) => {
    setState((prev) => ({ ...prev, selectedTeamId: teamId }));
  }, []);

  const setSortBy = useCallback((sortBy: SortOption) => {
    setState((prev) => ({
      ...prev,
      sortBy,
      teams: judgeService.sortTeams(prev.teams, sortBy),
    }));
  }, []);

  const toggleFilterShortlisted = useCallback(() => {
    setState((prev) => ({
      ...prev,
      filterShortlisted: !prev.filterShortlisted,
    }));
  }, []);

  const toggleShortlist = useCallback(async (teamId: string) => {
    await judgeService.toggleShortlist(teamId);
    setState((prev) => ({
      ...prev,
      teams: prev.teams.map((team) =>
        team.summary.id === teamId
          ? { ...team, shortlisted: !team.shortlisted }
          : team
      ),
    }));
  }, []);

  const updateNotes = useCallback(async (teamId: string, notes: string) => {
    await judgeService.updateJudgeNotes(teamId, notes);
    setState((prev) => ({
      ...prev,
      teams: prev.teams.map((team) =>
        team.summary.id === teamId
          ? { ...team, autoGeneratedSummary: { ...team.autoGeneratedSummary, judgeNotes: notes } }
          : team
      ),
    }));
  }, []);

  // Derived state
  const filteredTeams = state.filterShortlisted
    ? state.teams.filter((t) => t.shortlisted)
    : state.teams;

  const selectedTeam = state.teams.find(
    (t) => t.summary.id === state.selectedTeamId
  );

  return {
    ...state,
    filteredTeams,
    selectedTeam,
    selectTeam,
    setSortBy,
    toggleFilterShortlisted,
    toggleShortlist,
    updateNotes,
  };
}

// ============================================================================
// useToasts - Toast notification state management
// ============================================================================
export function useToasts() {
  const [toasts, setToasts] = useState<Toast[]>([]);

  const addToast = useCallback(
    (type: Toast["type"], message: string, duration: number = 4000) => {
      const id = `toast-${Date.now()}`;
      setToasts((prev) => [...prev, { id, type, message, duration }]);

      setTimeout(() => {
        setToasts((prev) => prev.filter((t) => t.id !== id));
      }, duration);
    },
    []
  );

  const dismissToast = useCallback((id: string) => {
    setToasts((prev) => prev.filter((t) => t.id !== id));
  }, []);

  return { toasts, addToast, dismissToast };
}

// ============================================================================
// useEvaluation - Modal and evaluation state
// ============================================================================
export function useEvaluation() {
  const [isNotesModalOpen, setNotesModalOpen] = useState(false);
  const [currentNotes, setCurrentNotes] = useState("");
  const [editingTeamId, setEditingTeamId] = useState<string | null>(null);

  const openNotesModal = useCallback((teamId: string, existingNotes: string) => {
    setEditingTeamId(teamId);
    setCurrentNotes(existingNotes);
    setNotesModalOpen(true);
  }, []);

  const closeNotesModal = useCallback(() => {
    setNotesModalOpen(false);
    setEditingTeamId(null);
    setCurrentNotes("");
  }, []);

  return {
    isNotesModalOpen,
    currentNotes,
    editingTeamId,
    setCurrentNotes,
    openNotesModal,
    closeNotesModal,
  };
}
